name: Sync FitTracker Data

on:
  repository_dispatch:
    types: [update_data]

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update JSON Data
        run: |
          echo '${{ github.event.client_payload.data }}' > fittracker-data.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "FitTracker Bot"
          git config --global user.email "bot@fittracker.local"
          git add fittracker-data.json
          git commit -m "Update FitTracker data [skip ci]" || exit 0
          git push
